-- ============================================================
-- SASYRA — Supabase Schema Migration
-- Creates all tables for migrating from localStorage to Supabase
-- Run this in the Supabase SQL Editor
-- ============================================================

-- 0. ENUMs
CREATE TYPE plan_type AS ENUM ('start', 'evidencia', 'clinicas', 'ia');
CREATE TYPE billing_type AS ENUM ('monthly', 'yearly');
CREATE TYPE module_type AS ENUM ('fisioterapia', 'terapiaOcupacional', 'nutricao', 'educacaoFisica', 'pediatria', 'crossfit', 'neuro');
CREATE TYPE appointment_type AS ENUM ('sessao', 'avaliacao', 'bloqueio');
CREATE TYPE appointment_status AS ENUM ('agendado', 'confirmado', 'concluido', 'faltou', 'cancelado');

-- 1. PROFILES (extends auth.users)
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  email TEXT,
  prof TEXT NOT NULL,
  crefito TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- 2. PATIENTS
CREATE TABLE patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  data_nasc TEXT,
  sexo TEXT,
  lateralidade TEXT,
  estado_civil TEXT,
  profissao TEXT,
  convenio TEXT,
  sessoes_auth TEXT,
  telefone TEXT,
  peso TEXT,
  altura TEXT,
  data_cadastro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  has_express BOOLEAN DEFAULT FALSE,
  express_date TEXT,
  meta_data JSONB DEFAULT '{}'::jsonb
);
CREATE INDEX idx_patients_user_id ON patients(user_id);
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can CRUD own patients" ON patients FOR ALL USING (auth.uid() = user_id);

-- 3. ASSESSMENTS
CREATE TABLE assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  data TEXT NOT NULL,
  queixa TEXT,
  queixa_key TEXT,
  local_dor JSONB DEFAULT '[]'::jsonb,
  carater_dor JSONB DEFAULT '[]'::jsonb,
  tempo_dor TEXT,
  melhora JSONB DEFAULT '[]'::jsonb,
  piora JSONB DEFAULT '[]'::jsonb,
  hda TEXT,
  comorbid JSONB DEFAULT '[]'::jsonb,
  antec JSONB DEFAULT '[]'::jsonb,
  meds TEXT,
  yellow_flags JSONB DEFAULT '[]'::jsonb,
  selected_red_flags JSONB DEFAULT '[]'::jsonb,
  eva_mov NUMERIC,
  eva_rep NUMERIC,
  avds JSONB DEFAULT '[]'::jsonb,
  obj_trat JSONB DEFAULT '[]'::jsonb,
  nivel_ati TEXT,
  postura JSONB DEFAULT '[]'::jsonb,
  marcha TEXT,
  edema TEXT,
  palpacao TEXT,
  sensib TEXT,
  reflexos TEXT,
  forca JSONB DEFAULT '[]'::jsonb,
  gonio JSONB DEFAULT '[]'::jsonb,
  tests JSONB DEFAULT '{}'::jsonb,
  obs TEXT,
  regiao TEXT,
  diagnostico_cinesio TEXT,
  -- express assessment fields
  vital_signs JSONB DEFAULT '{}'::jsonb,
  impressao_clinica TEXT,
  auto_cif JSONB DEFAULT '[]'::jsonb,
  recommended_scales JSONB DEFAULT '[]'::jsonb,
  honorario NUMERIC,
  is_express BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'complete',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_assessments_patient ON assessments(patient_id);
CREATE INDEX idx_assessments_user ON assessments(user_id);
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can CRUD own assessments" ON assessments FOR ALL USING (auth.uid() = user_id);

-- 4. LOGS (evolution/session records)
CREATE TABLE logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  data TEXT NOT NULL,
  eva NUMERIC,
  procedimentos JSONB DEFAULT '[]'::jsonb,
  resposta TEXT,
  evolucao TEXT,
  metas TEXT,
  escalas TEXT,
  escala_data JSONB DEFAULT '{}'::jsonb,
  pa TEXT,
  adms JSONB DEFAULT '[]'::jsonb,
  mrcs JSONB DEFAULT '[]'::jsonb,
  sessao_num INTEGER,
  spo2 TEXT,
  glucose TEXT,
  heart_rate TEXT,
  is_express_vital BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_logs_patient ON logs(patient_id);
CREATE INDEX idx_logs_user ON logs(user_id);
ALTER TABLE logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can CRUD own logs" ON logs FOR ALL USING (auth.uid() = user_id);

-- 5. APPOINTMENTS
CREATE TABLE appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT REFERENCES patients(id) ON DELETE SET NULL,
  patient_name TEXT NOT NULL,
  type appointment_type NOT NULL DEFAULT 'sessao',
  date TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  status appointment_status NOT NULL DEFAULT 'agendado',
  phone TEXT,
  convenio TEXT,
  has_red_flag BOOLEAN DEFAULT FALSE,
  professional_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_appointments_user ON appointments(user_id);
CREATE INDEX idx_appointments_date ON appointments(date);
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can CRUD own appointments" ON appointments FOR ALL USING (auth.uid() = user_id);

-- 6. SUBSCRIPTIONS
CREATE TABLE subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  plan plan_type NOT NULL DEFAULT 'start',
  billing billing_type NOT NULL DEFAULT 'monthly',
  start_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  next_billing TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days'),
  ai_analyses_used INTEGER NOT NULL DEFAULT 0,
  ai_period_start TEXT NOT NULL DEFAULT (TO_CHAR(NOW(), 'YYYY-MM')),
  ai_expansion JSONB DEFAULT '{}'::jsonb,
  extra_users JSONB DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can CRUD own subscription" ON subscriptions FOR ALL USING (auth.uid() = user_id);

-- 7. INVOICES
CREATE TABLE invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pago',
  description TEXT,
  invoice_date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_invoices_user ON invoices(user_id);
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can read own invoices" ON invoices FOR SELECT USING (auth.uid() = user_id);

-- 8. PATIENT_ACCESS (patient app sharing codes)
CREATE TABLE patient_access (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  code TEXT NOT NULL UNIQUE,
  views INTEGER NOT NULL DEFAULT 0,
  last_view TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, patient_id)
);
CREATE INDEX idx_patient_access_user ON patient_access(user_id);
CREATE INDEX idx_patient_access_code ON patient_access(code);
ALTER TABLE patient_access ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can CRUD own patient access" ON patient_access FOR ALL USING (auth.uid() = user_id);

-- 9. PATIENT_PLANS (patient app subscription plans)
CREATE TABLE patient_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  plan_type TEXT NOT NULL CHECK (plan_type IN ('mensal', 'trimestral', 'anual')),
  price NUMERIC NOT NULL,
  activated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  UNIQUE(user_id, patient_id)
);
ALTER TABLE patient_plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can CRUD own patient plans" ON patient_plans FOR ALL USING (auth.uid() = user_id);

-- 10. MODULE_DATA (per-student per-module JSONB storage)
-- Replaces: neuro_data_, ped_data_, cf_data_, nutri_data_, to_data_ patterns
CREATE TABLE module_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  module module_type NOT NULL,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, patient_id, module)
);
CREATE INDEX idx_module_data_user_patient ON module_data(user_id, patient_id);
ALTER TABLE module_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can CRUD own module data" ON module_data FOR ALL USING (auth.uid() = user_id);

-- 11. PE_DATA (Physical Education specific data)
-- Replaces pe_data[studentId] pattern (assessments, treinos, pse)
CREATE TABLE pe_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  data_type TEXT NOT NULL CHECK (data_type IN ('assessment', 'treino', 'pse')),
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_pe_data_patient ON pe_data(patient_id, data_type);
ALTER TABLE pe_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can CRUD own pe_data" ON pe_data FOR ALL USING (auth.uid() = user_id);

-- 12. FINANCEIRO (transactions)
CREATE TABLE transacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('receita', 'despesa')),
  patient_id BIGINT REFERENCES patients(id) ON DELETE SET NULL,
  data TEXT NOT NULL,
  descricao TEXT NOT NULL,
  valor NUMERIC NOT NULL,
  categoria TEXT,
  status TEXT DEFAULT 'pendente',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_transacoes_user ON transacoes(user_id);
ALTER TABLE transacoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can CRUD own transacoes" ON transacoes FOR ALL USING (auth.uid() = user_id);

-- Function to sync local data on first login
CREATE OR REPLACE FUNCTION sync_from_localstorage(p_user_id UUID, p_data JSONB)
RETURNS void AS $$
BEGIN
  -- Receives localStorage data dump and inserts into appropriate tables
  -- Called on first login after migration
  -- p_data keys: patients, assessments, logs, appointments, etc.
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to update updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_subscriptions_updated_at BEFORE UPDATE ON subscriptions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_module_data_updated_at BEFORE UPDATE ON module_data
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
