-- ============================================================
-- SASYRA — Schema v2: Production Scale
-- Normalized, partitioned, indexed for 5000+ concurrent users
-- ============================================================
-- INSTRUCTIONS:
--   1. Primeiro rode migration_001_schema.sql (se não rodou ainda)
--   2. Depois rode este script para atualizar para schema escalável
--   3. Opcional: `SELECT sasyra_analyze_workload()` após 7 dias de uso
-- ============================================================

-- ════════════════════════════════════════════════════════════
-- 0. EXTENSIONS
-- ════════════════════════════════════════════════════════════
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;  -- monitoramento de queries
CREATE EXTENSION IF NOT EXISTS pg_hint_plan;          -- hints de otimização
CREATE EXTENSION IF NOT EXISTS pgcrypto;              -- gen_random_uuid já incluso

-- ════════════════════════════════════════════════════════════
-- 1. REMOVE tabelas antigas e JSONBs normalizados (migration_001)
-- ════════════════════════════════════════════════════════════
-- Nota: Se migration_001 já foi rodada, drope tabelas substituídas:
-- DROP TABLE IF EXISTS module_data CASCADE;
-- DROP TABLE IF EXISTS pe_data CASCADE;
-- (assessments será migrada para partitioned + tables filhas)

-- ════════════════════════════════════════════════════════════
-- 2. ENUMS (ampliados)
-- ════════════════════════════════════════════════════════════
DO $$ BEGIN
  CREATE TYPE plan_type AS ENUM ('start', 'evidencia', 'clinicas', 'ia');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE billing_type AS ENUM ('monthly', 'yearly');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE appointment_type AS ENUM ('sessao', 'avaliacao', 'bloqueio');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE appointment_status AS ENUM ('agendado', 'confirmado', 'concluido', 'faltou', 'cancelado');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE module_type AS ENUM ('fisioterapia', 'terapiaOcupacional', 'nutricao', 'educacaoFisica', 'pediatria', 'crossfit', 'neuro');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ════════════════════════════════════════════════════════════
-- 3. PROFILES (mantido igual)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  email TEXT,
  prof TEXT NOT NULL,
  crefito TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read own profile" ON profiles;
CREATE POLICY "Users can read own profile" ON profiles FOR SELECT USING (auth.uid() = id);
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- ════════════════════════════════════════════════════════════
-- 4. PATIENTS — com índices compostos para busca textual
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome TEXT NOT NULL,
  data_nasc TEXT,
  sexo TEXT,
  lateralidade TEXT,
  estado_civil TEXT,
  profissao TEXT,
  convenio TEXT,
  sessoes_auth TEXT,
  telefone TEXT,
  peso TEXT,
  altura TEXT,
  data_cadastro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  has_express BOOLEAN DEFAULT FALSE,
  express_date TEXT,
  meta_data JSONB DEFAULT '{}'::jsonb,
  -- busca textual (preenchido por trigger)
  search_vector TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('portuguese', coalesce(nome,'') || ' ' || coalesce(telefone,'') || ' ' || coalesce(profissao,'') || ' ' || coalesce(convenio,''))
  ) STORED
);
CREATE INDEX IF NOT EXISTS idx_patients_user_id ON patients(user_id);
CREATE INDEX IF NOT EXISTS idx_patients_user_nome ON patients(user_id, nome);
CREATE INDEX IF NOT EXISTS idx_patients_search ON patients USING GIN(search_vector);
ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own patients" ON patients;
CREATE POLICY "Users can CRUD own patients" ON patients FOR ALL USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 5. ASSESSMENTS — particionada por user_id (hash em 16 partições)
--    JSONBs normalizados: forca → assessment_muscle_tests
--                         gonio → assessment_goniometry
--                         tests → assessment_special_tests
-- ════════════════════════════════════════════════════════════

-- Tabela pai (particionada)
CREATE TABLE IF NOT EXISTS assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL,
  patient_id BIGINT NOT NULL,
  data TEXT NOT NULL,
  queixa TEXT,
  queixa_key TEXT,
  local_dor JSONB DEFAULT '[]'::jsonb,     -- mantido: array pequeno e ~nunca indexado
  carater_dor JSONB DEFAULT '[]'::jsonb,
  tempo_dor TEXT,
  melhora JSONB DEFAULT '[]'::jsonb,
  piora JSONB DEFAULT '[]'::jsonb,
  hda TEXT,
  comorbid JSONB DEFAULT '[]'::jsonb,
  antec JSONB DEFAULT '[]'::jsonb,
  meds TEXT,
  yellow_flags JSONB DEFAULT '[]'::jsonb,
  selected_red_flags JSONB DEFAULT '[]'::jsonb,
  eva_mov NUMERIC,
  eva_rep NUMERIC,
  avds JSONB DEFAULT '[]'::jsonb,
  obj_trat JSONB DEFAULT '[]'::jsonb,
  nivel_ati TEXT,
  postura JSONB DEFAULT '[]'::jsonb,
  marcha TEXT,
  edema TEXT,
  palpacao TEXT,
  sensib TEXT,
  reflexos TEXT,
  obs TEXT,
  regiao TEXT,
  diagnostico_cinesio TEXT,
  vital_signs JSONB DEFAULT '{}'::jsonb,
  impressao_clinica TEXT,
  auto_cif JSONB DEFAULT '[]'::jsonb,
  recommended_scales JSONB DEFAULT '[]'::jsonb,
  honorario NUMERIC,
  is_express BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'complete',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id, user_id)
) PARTITION BY HASH (user_id);

-- 16 partições (escolha baseada em ~16 vCPUs no Supabase)
DO $$ BEGIN
  FOR i IN 0..15 LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS assessments_p%02d PARTITION OF assessments FOR VALUES WITH (MODULUS 16, REMAINDER %s)',
      i, i
    );
  END LOOP;
END $$;

-- Índices locais em cada partição (herdados automaticamente)
CREATE INDEX IF NOT EXISTS idx_assessments_patient_data ON assessments(patient_id, data DESC);
CREATE INDEX IF NOT EXISTS idx_assessments_user_data ON assessments(user_id, data DESC);
CREATE INDEX IF NOT EXISTS idx_assessments_created_at ON assessments(created_at DESC);

ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own assessments" ON assessments;
CREATE POLICY "Users can CRUD own assessments" ON assessments FOR ALL USING (auth.uid() = user_id);

-- Tabela normalizada: Testes Musculares (antes JSONB forca[])
CREATE TABLE IF NOT EXISTS assessment_muscle_tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  user_id UUID NOT NULL,
  muscle TEXT NOT NULL,
  value NUMERIC,
  UNIQUE(assessment_id, muscle)
);
CREATE INDEX IF NOT EXISTS idx_muscle_tests_assessment ON assessment_muscle_tests(assessment_id);
ALTER TABLE assessment_muscle_tests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own muscle tests" ON assessment_muscle_tests;
CREATE POLICY "Users can CRUD own muscle tests" ON assessment_muscle_tests FOR ALL USING (auth.uid() = user_id);

-- Tabela normalizada: Goniometria (antes JSONB gonio[])
CREATE TABLE IF NOT EXISTS assessment_goniometry (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  user_id UUID NOT NULL,
  joint TEXT NOT NULL,
  movement TEXT NOT NULL,
  value NUMERIC,
  UNIQUE(assessment_id, joint, movement)
);
CREATE INDEX IF NOT EXISTS idx_goniometry_assessment ON assessment_goniometry(assessment_id);
ALTER TABLE assessment_goniometry ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own goniometry" ON assessment_goniometry;
CREATE POLICY "Users can CRUD own goniometry" ON assessment_goniometry FOR ALL USING (auth.uid() = user_id);

-- Tabela normalizada: Testes Especiais (antes JSONB tests{})
CREATE TABLE IF NOT EXISTS assessment_special_tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT NOT NULL,
  user_id UUID NOT NULL,
  test_name TEXT NOT NULL,
  result TEXT,
  notes TEXT,
  UNIQUE(assessment_id, test_name)
);
CREATE INDEX IF NOT EXISTS idx_special_tests_assessment ON assessment_special_tests(assessment_id);
ALTER TABLE assessment_special_tests ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own special tests" ON assessment_special_tests;
CREATE POLICY "Users can CRUD own special tests" ON assessment_special_tests FOR ALL USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 6. LOGS — particionada por user_id (8 partições)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL,
  patient_id BIGINT NOT NULL,
  data TEXT NOT NULL,
  eva NUMERIC,
  procedimentos JSONB DEFAULT '[]'::jsonb,
  resposta TEXT,
  evolucao TEXT,
  metas TEXT,
  escalas TEXT,
  escala_data JSONB DEFAULT '{}'::jsonb,
  pa TEXT,
  adms JSONB DEFAULT '[]'::jsonb,
  mrcs JSONB DEFAULT '[]'::jsonb,
  sessao_num INTEGER,
  spo2 TEXT,
  glucose TEXT,
  heart_rate TEXT,
  is_express_vital BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id, user_id)
) PARTITION BY HASH (user_id);

DO $$ BEGIN
  FOR i IN 0..7 LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS logs_p%02d PARTITION OF logs FOR VALUES WITH (MODULUS 8, REMAINDER %s)',
      i, i
    );
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_logs_patient_data ON logs(patient_id, data DESC);
CREATE INDEX IF NOT EXISTS idx_logs_user_data ON logs(user_id, data DESC);

ALTER TABLE logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own logs" ON logs;
CREATE POLICY "Users can CRUD own logs" ON logs FOR ALL USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 7. APPOINTMENTS — índices para busca por data + status
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT REFERENCES patients(id) ON DELETE SET NULL,
  patient_name TEXT NOT NULL,
  type appointment_type NOT NULL DEFAULT 'sessao',
  date TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  status appointment_status NOT NULL DEFAULT 'agendado',
  phone TEXT,
  convenio TEXT,
  has_red_flag BOOLEAN DEFAULT FALSE,
  professional_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_appointments_user_date ON appointments(user_id, date, status);
CREATE INDEX IF NOT EXISTS idx_appointments_user_start ON appointments(user_id, date, start_time);
CREATE INDEX IF NOT EXISTS idx_appointments_date_status ON appointments(date, status) WHERE status IN ('agendado', 'confirmado');
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own appointments" ON appointments;
CREATE POLICY "Users can CRUD own appointments" ON appointments FOR ALL USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 8. SUBSCRIPTIONS — cache-ready
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  plan plan_type NOT NULL DEFAULT 'start',
  billing billing_type NOT NULL DEFAULT 'monthly',
  start_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  next_billing TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days'),
  ai_analyses_used INTEGER NOT NULL DEFAULT 0,
  ai_period_start TEXT NOT NULL DEFAULT (TO_CHAR(NOW(), 'YYYY-MM')),
  ai_expansion JSONB DEFAULT '{}'::jsonb,
  extra_users JSONB DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_subscriptions_next_billing ON subscriptions(next_billing) WHERE plan != 'start';
ALTER TABLE subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own subscription" ON subscriptions;
CREATE POLICY "Users can CRUD own subscription" ON subscriptions FOR ALL USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 9. INVOICES — particionada (4 partições)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL,
  amount NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pago',
  description TEXT,
  invoice_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id, user_id)
) PARTITION BY HASH (user_id);

DO $$ BEGIN
  FOR i IN 0..3 LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS invoices_p%02d PARTITION OF invoices FOR VALUES WITH (MODULUS 4, REMAINDER %s)',
      i, i
    );
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_invoices_user_date ON invoices(user_id, invoice_date DESC);

ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can read own invoices" ON invoices;
CREATE POLICY "Users can read own invoices" ON invoices FOR SELECT USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 10. PATIENT_ACCESS
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS patient_access (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  code TEXT NOT NULL UNIQUE,
  views INTEGER NOT NULL DEFAULT 0,
  last_view TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, patient_id)
);
CREATE INDEX IF NOT EXISTS idx_patient_access_user ON patient_access(user_id);
CREATE INDEX IF NOT EXISTS idx_patient_access_code ON patient_access(code);
ALTER TABLE patient_access ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own patient access" ON patient_access;
CREATE POLICY "Users can CRUD own patient access" ON patient_access FOR ALL USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 11. PATIENT_PLANS
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS patient_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  plan_type TEXT NOT NULL CHECK (plan_type IN ('mensal', 'trimestral', 'anual')),
  price NUMERIC NOT NULL,
  activated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  UNIQUE(user_id, patient_id)
);
CREATE INDEX IF NOT EXISTS idx_patient_plans_active ON patient_plans(user_id) WHERE active = TRUE;
ALTER TABLE patient_plans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own patient plans" ON patient_plans;
CREATE POLICY "Users can CRUD own patient plans" ON patient_plans FOR ALL USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 12. PER-MODULE TABLES (cada módulo com colunas tipadas)
--     Substitui module_data JSONB catch-all
-- ════════════════════════════════════════════════════════════

-- 12a. NEURO
CREATE TABLE IF NOT EXISTS neuro_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  -- Anamnese
  diagnostico_medico TEXT,
  tempo_lesao TEXT,
  mecanismo_lesao TEXT,
  lado_afetado TEXT,
  historico_neuro TEXT,
  medicacoes TEXT,
  comorbidades_neuro JSONB DEFAULT '[]'::jsonb,
  sintomas JSONB DEFAULT '[]'::jsonb,
  avds_neuro JSONB DEFAULT '[]'::jsonb,
  -- Escalas
  mas_flexores_cotovelo_d NUMERIC,
  mas_flexores_cotovelo_e NUMERIC,
  mas_extensores_joelho_d NUMERIC,
  mas_extensores_joelho_e NUMERIC,
  mas_flexores_plantares_d NUMERIC,
  mas_flexores_plantares_e NUMERIC,
  bbs_senta_pe NUMERIC,
  bbs_pe_sem_apoio NUMERIC,
  bbs_transferencias NUMERIC,
  bbs_alcance_frente NUMERIC,
  bbs_apoio_unipodal NUMERIC,
  mif_alimentacao NUMERIC,
  mif_higiene NUMERIC,
  mif_banho NUMERIC,
  mif_vestir_superior NUMERIC,
  mif_vestir_inferior NUMERIC,
  mif_uso_banheiro NUMERIC,
  -- Exame físico
  tono TEXT,
  sensibilidade JSONB DEFAULT '[]'::jsonb,
  coordenacao JSONB DEFAULT '[]'::jsonb,
  tipo_marcha JSONB DEFAULT '[]'::jsonb,
  reflexos JSONB DEFAULT '[]'::jsonb,
  -- Força muscular (MRC)
  forca_deltoide_d NUMERIC,
  forca_deltoide_e NUMERIC,
  forca_biceps_d NUMERIC,
  forca_biceps_e NUMERIC,
  forca_extensor_punho_d NUMERIC,
  forca_extensor_punho_e NUMERIC,
  forca_flexor_quadril_d NUMERIC,
  forca_flexor_quadril_e NUMERIC,
  forca_quadriceps_d NUMERIC,
  forca_quadriceps_e NUMERIC,
  forca_tibial_anterior_d NUMERIC,
  forca_tibial_anterior_e NUMERIC,
  -- Evolução
  evolucao_neuro TEXT,
  data TEXT NOT NULL DEFAULT (TO_CHAR(NOW(), 'YYYY-MM-DD')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, patient_id)
);
CREATE INDEX IF NOT EXISTS idx_neuro_user_patient ON neuro_data(user_id, patient_id);
ALTER TABLE neuro_data ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD neuro data" ON neuro_data;
CREATE POLICY "Users can CRUD neuro data" ON neuro_data FOR ALL USING (auth.uid() = user_id);

-- 12b. PEDIATRIA
CREATE TABLE IF NOT EXISTS ped_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  queixa_principal TEXT,
  diagnostico_medico TEXT,
  historia_gestacional TEXT,
  tipo_parto TEXT,
  prematuridade TEXT,
  apgar TEXT,
  marcos_motores JSONB DEFAULT '[]'::jsonb,
  comorbidades JSONB DEFAULT '[]'::jsonb,
  tonus TEXT,
  reflexos_primitivos JSONB DEFAULT '[]'::jsonb,
  coordenacao JSONB DEFAULT '[]'::jsonb,
  gmfcs TEXT,
  aims_score TEXT,
  mchat JSONB DEFAULT '[]'::jsonb,
  objetivos_funcionais TEXT,
  atividades_terapeuticas JSONB DEFAULT '[]'::jsonb,
  frequencia TEXT,
  orientacoes_cuidador TEXT,
  evolucao TEXT,
  data TEXT NOT NULL DEFAULT (TO_CHAR(NOW(), 'YYYY-MM-DD')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, patient_id)
);
CREATE INDEX IF NOT EXISTS idx_ped_user_patient ON ped_data(user_id, patient_id);
ALTER TABLE ped_data ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD ped data" ON ped_data;
CREATE POLICY "Users can CRUD ped data" ON ped_data FOR ALL USING (auth.uid() = user_id);

-- 12c. CROSSFIT
CREATE TABLE IF NOT EXISTS cf_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  nome_atleta TEXT,
  idade_atleta TEXT,
  sexo_atleta TEXT,
  tempo_crossfit TEXT,
  modalidades JSONB DEFAULT '[]'::jsonb,
  lesoes_previas JSONB DEFAULT '[]'::jsonb,
  restricoes_movimentos JSONB DEFAULT '[]'::jsonb,
  nivel_atleta TEXT,
  objetivos JSONB DEFAULT '[]'::jsonb,
  frequencia_semanal TEXT,
  snatch_rm TEXT,
  clean_jerk_rm TEXT,
  back_squat_rm TEXT,
  front_squat_rm TEXT,
  deadlift_rm TEXT,
  bench_press_rm TEXT,
  shoulder_press_rm TEXT,
  -- Benchmark WODs: histórico armazenado em JSONB (estrutura variável por WOD)
  benchmarks_historico JSONB DEFAULT '[]'::jsonb,
  -- Treinos: cada treino é um registro separado
  evolucao TEXT,
  data TEXT NOT NULL DEFAULT (TO_CHAR(NOW(), 'YYYY-MM-DD')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, patient_id)
);
CREATE INDEX IF NOT EXISTS idx_cf_user_patient ON cf_data(user_id, patient_id);
ALTER TABLE cf_data ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD cf data" ON cf_data;
CREATE POLICY "Users can CRUD cf data" ON cf_data FOR ALL USING (auth.uid() = user_id);

-- 12d. NUTRIÇÃO
CREATE TABLE IF NOT EXISTS nutri_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  queixa_nutri TEXT,
  historico_peso TEXT,
  alergias JSONB DEFAULT '[]'::jsonb,
  restricoes JSONB DEFAULT '[]'::jsonb,
  suplementos JSONB DEFAULT '[]'::jsonb,
  medicamentos JSONB DEFAULT '[]'::jsonb,
  cirurgias JSONB DEFAULT '[]'::jsonb,
  doencas JSONB DEFAULT '[]'::jsonb,
  historico_familiar TEXT,
  habitos_vida TEXT,
  consumo_agua TEXT,
  sono TEXT,
  peso_atual TEXT,
  altura_atual TEXT,
  cintura TEXT,
  quadril TEXT,
  pescoco TEXT,
  sexo_rcq TEXT,
  formula_bmr TEXT,
  pal TEXT,
  must_bmi NUMERIC,
  must_perda_peso NUMERIC,
  must_doenca_aguda BOOLEAN,
  sarcf_forca NUMERIC,
  sarcf_andar NUMERIC,
  sarcf_levantar NUMERIC,
  sarcf_escadas NUMERIC,
  sarcf_quedas NUMERIC,
  refeicoes JSONB DEFAULT '[]'::jsonb,
  bioquimica JSONB DEFAULT '[]'::jsonb,
  ipaq JSONB DEFAULT '{}'::jsonb,
  evolucao TEXT,
  conduta_nutri TEXT,
  data TEXT NOT NULL DEFAULT (TO_CHAR(NOW(), 'YYYY-MM-DD')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, patient_id)
);
CREATE INDEX IF NOT EXISTS idx_nutri_user_patient ON nutri_data(user_id, patient_id);
ALTER TABLE nutri_data ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD nutri data" ON nutri_data;
CREATE POLICY "Users can CRUD nutri data" ON nutri_data FOR ALL USING (auth.uid() = user_id);

-- 12e. TERAPIA OCUPACIONAL
CREATE TABLE IF NOT EXISTS to_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  diagnostico_medico TEXT,
  queixa_to TEXT,
  ocupacao TEXT,
  rotina TEXT,
  domicilio TEXT,
  acompanhante TEXT,
  tecnologia_assistiva JSONB DEFAULT '[]'::jsonb,
  adaptacoes JSONB DEFAULT '[]'::jsonb,
  condicoes_associadas JSONB DEFAULT '[]'::jsonb,
  avds JSONB DEFAULT '[]'::jsonb,
  aivds JSONB DEFAULT '[]'::jsonb,
  lazer JSONB DEFAULT '[]'::jsonb,
  trabalho_prod JSONB DEFAULT '[]'::jsonb,
  copm_metas_1 TEXT, copm_metas_2 TEXT, copm_metas_3 TEXT, copm_metas_4 TEXT, copm_metas_5 TEXT,
  copm_desempenho_1 NUMERIC, copm_desempenho_2 NUMERIC, copm_desempenho_3 NUMERIC, copm_desempenho_4 NUMERIC, copm_desempenho_5 NUMERIC,
  copm_satisfacao_1 NUMERIC, copm_satisfacao_2 NUMERIC, copm_satisfacao_3 NUMERIC, copm_satisfacao_4 NUMERIC, copm_satisfacao_5 NUMERIC,
  barthel_alimentacao NUMERIC, barthel_banho NUMERIC, barthel_vestir NUMERIC, barthel_arrumar NUMERIC, barthel_uso_banheiro NUMERIC,
  barthel_controle_bexiga NUMERIC, barthel_controle_intestino NUMERIC, barthel_transferencia NUMERIC, barthel_marcha NUMERIC, barthel_escadas NUMERIC,
  lawton_telefone NUMERIC, lawton_compras NUMERIC, lawton_comida NUMERIC, lawton_casa NUMERIC, lawton_lavanderia NUMERIC,
  lawton_transporte NUMERIC, lawton_medicamentos NUMERIC, lawton_financas NUMERIC,
  forca_pinca TEXT,
  forca_preensao TEXT,
  jebsen_time TEXT,
  manipulacao_fina TEXT,
  sensibilidade JSONB DEFAULT '[]'::jsonb,
  estereognosia JSONB DEFAULT '[]'::jsonb,
  mini_mental JSONB DEFAULT '{}'::jsonb,
  memoria JSONB DEFAULT '[]'::jsonb,
  atencao JSONB DEFAULT '[]'::jsonb,
  funcao_executiva JSONB DEFAULT '[]'::jsonb,
  barreiras JSONB DEFAULT '[]'::jsonb,
  risco_queda BOOLEAN DEFAULT FALSE,
  evolucao TEXT,
  metas TEXT,
  data TEXT NOT NULL DEFAULT (TO_CHAR(NOW(), 'YYYY-MM-DD')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, patient_id)
);
CREATE INDEX IF NOT EXISTS idx_to_user_patient ON to_data(user_id, patient_id);
ALTER TABLE to_data ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD to data" ON to_data;
CREATE POLICY "Users can CRUD to data" ON to_data FOR ALL USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 13. PE_DATA — tabelas específicas para Educação Física
--     Substitui pe_data[studentId] { assessments[], treinos[], pse[] }
-- ════════════════════════════════════════════════════════════

-- 13a. PE Assessments (avaliações físicas)
CREATE TABLE IF NOT EXISTS pe_assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  data TEXT NOT NULL,
  percentual_gordura NUMERIC,
  massa_magra NUMERIC,
  massa_gorda NUMERIC,
  agua_total NUMERIC,
  angulo_fase NUMERIC,
  imc NUMERIC,
  protocolo TEXT,
  referencia TEXT,
  densidade_corporal NUMERIC,
  vo2max NUMERIC,
  rm NUMERIC,
  peso NUMERIC,
  detalhes JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pe_assessments_patient ON pe_assessments(patient_id, data DESC);
ALTER TABLE pe_assessments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD pe assessments" ON pe_assessments;
CREATE POLICY "Users can CRUD pe assessments" ON pe_assessments FOR ALL USING (auth.uid() = user_id);

-- 13b. PE Treinos (prescrições)
CREATE TABLE IF NOT EXISTS pe_treinos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  data_prescricao TEXT NOT NULL,
  objetivo TEXT,
  nivel TEXT,
  divisao TEXT,
  estrutura JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_pe_treinos_patient ON pe_treinos(patient_id, data_prescricao DESC);
ALTER TABLE pe_treinos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD pe treinos" ON pe_treinos;
CREATE POLICY "Users can CRUD pe treinos" ON pe_treinos FOR ALL USING (auth.uid() = user_id);

-- 13c. PE PSE Sessions (monitoramento de carga)
CREATE TABLE IF NOT EXISTS pe_pse_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  data TEXT NOT NULL,
  sessoes JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, patient_id, data)
);
CREATE INDEX IF NOT EXISTS idx_pe_pse_patient ON pe_pse_sessions(patient_id, data DESC);
ALTER TABLE pe_pse_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD pe pse" ON pe_pse_sessions;
CREATE POLICY "Users can CRUD pe pse" ON pe_pse_sessions FOR ALL USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 14. TRANSACOES (Financeiro) — particionada (8 partições)
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS transacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id UUID NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('receita', 'despesa')),
  patient_id BIGINT,
  data TEXT NOT NULL,
  descricao TEXT NOT NULL,
  valor NUMERIC NOT NULL,
  categoria TEXT,
  status TEXT DEFAULT 'pendente',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (id, user_id)
) PARTITION BY HASH (user_id);

DO $$ BEGIN
  FOR i IN 0..7 LOOP
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS transacoes_p%02d PARTITION OF transacoes FOR VALUES WITH (MODULUS 8, REMAINDER %s)',
      i, i
    );
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS idx_transacoes_user_data ON transacoes(user_id, data DESC);
CREATE INDEX IF NOT EXISTS idx_transacoes_type ON transacoes(user_id, type);

ALTER TABLE transacoes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can CRUD own transacoes" ON transacoes;
CREATE POLICY "Users can CRUD own transacoes" ON transacoes FOR ALL USING (auth.uid() = user_id);

-- ════════════════════════════════════════════════════════════
-- 15. CACHE LAYER — tabela de cache para leituras frequentes
-- ════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS sasyra_cache (
  cache_key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '5 minutes'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cache_expires ON sasyra_cache(expires_at);

-- Função de leitura com cache
CREATE OR REPLACE FUNCTION sasyra_cache_get(p_key TEXT, p_ttl_seconds INT DEFAULT 300)
RETURNS JSONB AS $$
DECLARE
  v_value JSONB;
BEGIN
  SELECT value INTO v_value FROM sasyra_cache
    WHERE cache_key = p_key AND expires_at > NOW();
  RETURN v_value;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Função de escrita no cache
CREATE OR REPLACE FUNCTION sasyra_cache_set(p_key TEXT, p_value JSONB, p_ttl_seconds INT DEFAULT 300)
RETURNS VOID AS $$
BEGIN
  INSERT INTO sasyra_cache (cache_key, value, expires_at)
  VALUES (p_key, p_value, NOW() + (p_ttl_seconds || ' seconds')::INTERVAL)
  ON CONFLICT (cache_key) DO UPDATE SET
    value = EXCLUDED.value,
    expires_at = EXCLUDED.expires_at;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Job de limpeza do cache (pode ser chamado por pg_cron ou manualmente)
CREATE OR REPLACE FUNCTION sasyra_cache_cleanup()
RETURNS INT AS $$
DECLARE
  v_deleted INT;
BEGIN
  DELETE FROM sasyra_cache WHERE expires_at < NOW();
  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN v_deleted;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ════════════════════════════════════════════════════════════
-- 16. FUNÇÕES DE ALTA PERFORMANCE (SECURITY DEFINER)
--     Bypass RLS para operações bulk — chamadas pelo backend
-- ════════════════════════════════════════════════════════════

-- Batch insert assessments + normalized sub-records
CREATE OR REPLACE FUNCTION sasyra_batch_insert_assessment(
  p_user_id UUID,
  p_patient_id BIGINT,
  p_assessment JSONB,
  p_muscle_tests JSONB DEFAULT '[]'::jsonb,
  p_goniometry JSONB DEFAULT '[]'::jsonb,
  p_special_tests JSONB DEFAULT '{}'::jsonb
) RETURNS BIGINT AS $$
DECLARE
  v_assessment_id BIGINT;
  v_item JSONB;
BEGIN
  -- Insert main assessment record
  INSERT INTO assessments (
    user_id, patient_id, data, queixa, queixa_key, local_dor, carater_dor,
    tempo_dor, melhora, piora, hda, comorbid, antec, meds,
    yellow_flags, selected_red_flags, eva_mov, eva_rep, avds, obj_trat,
    nivel_ati, postura, marcha, edema, palpacao, sensib, reflexos,
    obs, regiao, diagnostico_cinesio, vital_signs, impressao_clinica,
    auto_cif, recommended_scales, honorario, is_express, status
  ) VALUES (
    p_user_id, p_patient_id,
    p_assessment->>'data', p_assessment->>'queixa', p_assessment->>'queixaKey',
    COALESCE(p_assessment->'localDor', '[]'::jsonb),
    COALESCE(p_assessment->'caraterDor', '[]'::jsonb),
    p_assessment->>'tempoDor', COALESCE(p_assessment->'melhora', '[]'::jsonb),
    COALESCE(p_assessment->'piora', '[]'::jsonb), p_assessment->>'hda',
    COALESCE(p_assessment->'comorbid', '[]'::jsonb),
    COALESCE(p_assessment->'antec', '[]'::jsonb), p_assessment->>'meds',
    COALESCE(p_assessment->'yellowFlagsState', '[]'::jsonb),
    COALESCE(p_assessment->'selectedRedFlags', '[]'::jsonb),
    (p_assessment->>'evaMov')::NUMERIC, (p_assessment->>'evaRep')::NUMERIC,
    COALESCE(p_assessment->'avds', '[]'::jsonb),
    COALESCE(p_assessment->'objTrat', '[]'::jsonb),
    p_assessment->>'nivelAti', COALESCE(p_assessment->'postura', '[]'::jsonb),
    p_assessment->>'marcha', p_assessment->>'edema', p_assessment->>'palpacao',
    p_assessment->>'sensib', p_assessment->>'reflexos', p_assessment->>'obs',
    p_assessment->>'regiao', p_assessment->>'diagnosticoCinesio',
    COALESCE(p_assessment->'vitalSigns', '{}'::jsonb),
    p_assessment->>'impressaoClinica',
    COALESCE(p_assessment->'autoCIF', '[]'::jsonb),
    COALESCE(p_assessment->'recommendedScales', '[]'::jsonb),
    (p_assessment->>'honorario')::NUMERIC,
    COALESCE((p_assessment->>'isExpress')::BOOLEAN, FALSE),
    COALESCE(p_assessment->>'status', 'complete')
  ) RETURNING id INTO v_assessment_id;

  -- Insert normalized muscle tests
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_muscle_tests)
  LOOP
    INSERT INTO assessment_muscle_tests (assessment_id, user_id, muscle, value)
    VALUES (v_assessment_id, p_user_id, v_item->>'muscle', (v_item->>'value')::NUMERIC);
  END LOOP;

  -- Insert normalized goniometry
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_goniometry)
  LOOP
    INSERT INTO assessment_goniometry (assessment_id, user_id, joint, movement, value)
    VALUES (v_assessment_id, p_user_id, v_item->>'joint', v_item->>'movement', (v_item->>'value')::NUMERIC);
  END LOOP;

  -- Insert normalized special tests
  FOR v_item IN SELECT * FROM jsonb_each(p_special_tests)
  LOOP
    INSERT INTO assessment_special_tests (assessment_id, user_id, test_name, result)
    VALUES (v_assessment_id, p_user_id, v_item.key, v_item.value->>0);
  END LOOP;

  RETURN v_assessment_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
   ROWS 1;

-- Batch fetch: assessment + related normalized data (1+N → 1 query via JOIN)
CREATE OR REPLACE FUNCTION sasyra_get_full_assessment(
  p_assessment_id BIGINT,
  p_user_id UUID
) RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
BEGIN
  SELECT jsonb_build_object(
    'assessment', row_to_json(a)::jsonb,
    'muscle_tests', COALESCE((SELECT jsonb_agg(row_to_json(mt)::jsonb) FROM assessment_muscle_tests mt WHERE mt.assessment_id = a.id), '[]'::jsonb),
    'goniometry', COALESCE((SELECT jsonb_agg(row_to_json(g)::jsonb) FROM assessment_goniometry g WHERE g.assessment_id = a.id), '[]'::jsonb),
    'special_tests', COALESCE((SELECT jsonb_object_agg(st.test_name, st.result) FROM assessment_special_tests st WHERE st.assessment_id = a.id), '{}'::jsonb)
  ) INTO v_result
  FROM assessments a
  WHERE a.id = p_assessment_id AND a.user_id = p_user_id;

  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
   STABLE;

-- ════════════════════════════════════════════════════════════
-- 17. PAGINAÇÃO — função genérica para queries paginadas
-- ════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION sasyra_paginate(
  p_sql TEXT,
  p_page INT DEFAULT 1,
  p_per_page INT DEFAULT 50,
  p_max_per_page INT DEFAULT 200
) RETURNS JSONB AS $$
DECLARE
  v_offset INT;
  v_limit INT;
  v_total INT;
  v_rows JSONB;
BEGIN
  v_limit := LEAST(p_per_page, p_max_per_page);
  v_offset := (GREATEST(p_page, 1) - 1) * v_limit;

  -- Count total (expects the SQL to work with COUNT(*))
  EXECUTE 'SELECT COUNT(*) FROM (' || p_sql || ') AS _count' INTO v_total;

  -- Fetch paginated rows
  EXECUTE 'SELECT COALESCE(jsonb_agg(row_to_json(t)), ''[]''::jsonb) FROM (' ||
    p_sql || ' LIMIT ' || v_limit || ' OFFSET ' || v_offset || ') AS t'
  INTO v_rows;

  RETURN jsonb_build_object(
    'data', v_rows,
    'total', v_total,
    'page', p_page,
    'per_page', v_limit,
    'total_pages', CEIL(v_total::NUMERIC / v_limit)::INT
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER
   STABLE;

-- ════════════════════════════════════════════════════════════
-- 18. TRIGGERS
-- ════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Aplicar trigger em todas as tabelas com updated_at
DO $$ DECLARE
  t TEXT;
BEGIN
  FOR t IN SELECT table_name FROM information_schema.columns
    WHERE column_name = 'updated_at' AND table_schema = 'public'
  LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS trg_%s_updated_at ON %s; CREATE TRIGGER trg_%s_updated_at BEFORE UPDATE ON %s FOR EACH ROW EXECUTE FUNCTION update_updated_at_column()',
      t, t, t, t
    );
  END LOOP;
END $$;

-- ════════════════════════════════════════════════════════════
-- 19. ANALYSE DE WORKLOAD (para DBA)
-- ════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION sasyra_analyze_workload()
RETURNS TABLE (
  query_text TEXT,
  calls BIGINT,
  total_time NUMERIC,
  mean_time NUMERIC,
  rows BIGINT,
  shared_blks_hit BIGINT,
  shared_blks_read BIGINT
) AS $$
  SELECT query, calls, total_exec_time, mean_exec_time, rows,
         shared_blks_hit, shared_blks_read
  FROM pg_stat_statements
  WHERE query LIKE '%sasyra%' OR query LIKE '%assessments%' OR query LIKE '%patients%'
  ORDER BY total_exec_time DESC
  LIMIT 20;
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

-- ════════════════════════════════════════════════════════════
-- 20. MIGRAÇÃO DE DADOS: localStorage → Supabase
-- ════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION sasyra_migrate_from_localstorage(p_user_id UUID, p_data JSONB)
RETURNS JSONB AS $$
DECLARE
  v_result JSONB;
  v_patients INT := 0;
  v_assessments INT := 0;
  v_logs INT := 0;
  v_errors JSONB := '[]'::jsonb;
  v_item JSONB;
BEGIN
  -- Migrate patients
  IF p_data ? 'patients' THEN
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_data->'patients')
    LOOP
      BEGIN
        INSERT INTO patients (user_id, nome, data_nasc, sexo, lateralidade, estado_civil, profissao, convenio, sessoes_auth, telefone, peso, altura, has_express, express_date)
        VALUES (p_user_id, v_item->>'nome', v_item->>'dataNasc', v_item->>'sexo', v_item->>'lateralidade', v_item->>'estadoCivil', v_item->>'profissao', v_item->>'convenio', v_item->>'sessoesAuth', v_item->>'telefone', v_item->>'peso', v_item->>'altura', COALESCE((v_item->>'hasExpress')::BOOLEAN, FALSE), v_item->>'expressDate');
        v_patients := v_patients + 1;
      EXCEPTION WHEN OTHERS THEN
        v_errors := v_errors || jsonb_build_object('type', 'patient', 'nome', v_item->>'nome', 'error', SQLERRM);
      END;
    END LOOP;
  END IF;

  -- More migrations can be added here (assessments, logs, etc.)

  v_result := jsonb_build_object(
    'patients_migrated', v_patients,
    'assessments_migrated', v_assessments,
    'logs_migrated', v_logs,
    'errors', v_errors
  );
  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ════════════════════════════════════════════════════════════
-- 21. NOTIFICAÇÃO: configuração do Realtime (opcional)
-- ════════════════════════════════════════════════════════════
-- Habilita Realtime para tabelas que precisam de subscribe em tempo real
-- (ex: appointments para notificar de novos agendamentos)
-- Descomente se necessário:
-- ALTER PUBLICATION supabase_realtime ADD TABLE appointments;
-- ALTER PUBLICATION supabase_realtime ADD TABLE patients;

-- ════════════════════════════════════════════════════════════
-- FIM DA MIGRAÇÃO
-- ════════════════════════════════════════════════════════════
-- Para verificar: SELECT count(*) FROM assessments; SELECT count(*) FROM logs;
-- Para monitorar: SELECT * FROM sasyra_analyze_workload();
